@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Ext(ext1, "External System")
ContainerQueue_Ext(extEvents, "External Event Stream")

System_Boundary(sys, "Pet Store") {
  Container(api, "API Gateway")

  Container_Boundary(domainServices, "Domain Services") {
    Container(pet, "Pet")
    Container(store, "Store")
    Container(user, "User")
  }

  Container_Boundary(writeServices, "Write Services") {
    Container(writeWorker, "Write Worker")
    ContainerQueue(writes, "Write Events")
    Container(publisher, "Publisher")
  }
  
  Container(ingester, "Ingester")
  
  ContainerDb(db, "Document Store")
}

Rel_D(ext1, api, "API Calls", "HTTPS")

Rel(ingester, extEvents, "Subscribes")
Rel_U(ingester, api, "")

Rel_D(api, domainServices, "")


Rel_D(domainServices, writes, "Publishes")
Rel(domainServices, db, "Reads")

Rel_U(writeWorker, writes, "Subscribes")
Rel_L(writeWorker, db, "Writes")

Rel_R(publisher, writes, "Subscribes")
Rel(publisher, extEvents, "Publishes")

@enduml