@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Ext(ext1, "External System")

System_Boundary(sys, "Pet Store") {
  Container(api, "API Gateway")
  Container(trans, "Transaction Service")

  Container(write, "Write Service")
  Container(read, "Read Service")

  Container(writeWorker, "Write Service Worker")

  ContainerQueue(events, "Internal Event Stream")

  Container(ingester, "Ingester Service")
  Container(publisher, "Publisher Service")

  ContainerDb(db, "Document Store")

}

ContainerQueue_Ext(extEvents, "External Event Stream")
System_Ext(ext2, "External System")

Rel(ext1, api, "API Calls", "HTTPS")
Rel(api, trans, "")

Rel(trans, write, "")
Rel(trans, read, "")

Rel_D(write, events, "Publishes")
Rel_D(read, db, "Reads")

Rel_D(writeWorker, events, "Subscribes, Consumes")
Rel_U(writeWorker, db, "Writes")

Rel_D(ingester, extEvents, "Subscribes, Consumes")
Rel_U(ingester, write, "Calls")

Rel_D(publisher, extEvents, "Publishes")
Rel_U(publisher, events, "Subscribes, Consumes")

Rel_U(ext2, extEvents, "Publishes, Subscribes, Consumes")
@enduml
