name: Generate PlantUML Diagrams
on: 
  workflow_dispatch:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Render PlantUML to wiki
        uses: cjgibbons/render-latest-plantuml-to-wiki-action@v2
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
