name: generate plantuml
on: 
  workflow_dispatch:
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
